
package  org.wuyechun.util.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InfoSearchServices", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.16.7.107:3164/InfoSearchServices.asmx?WSDL")
public class InfoSearchServices
    extends Service
{

    private final static URL INFOSEARCHSERVICES_WSDL_LOCATION;
    private final static WebServiceException INFOSEARCHSERVICES_EXCEPTION;
    private final static QName INFOSEARCHSERVICES_QNAME = new QName("http://tempuri.org/", "InfoSearchServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.7.107:3164/InfoSearchServices.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INFOSEARCHSERVICES_WSDL_LOCATION = url;
        INFOSEARCHSERVICES_EXCEPTION = e;
    }

    public InfoSearchServices() {
        super(__getWsdlLocation(), INFOSEARCHSERVICES_QNAME);
    }

    public InfoSearchServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), INFOSEARCHSERVICES_QNAME, features);
    }

    public InfoSearchServices(URL wsdlLocation) {
        super(wsdlLocation, INFOSEARCHSERVICES_QNAME);
    }

    public InfoSearchServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INFOSEARCHSERVICES_QNAME, features);
    }

    public InfoSearchServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfoSearchServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InfoSearchServicesSoap
     */
    @WebEndpoint(name = "InfoSearchServicesSoap")
    public InfoSearchServicesSoap getInfoSearchServicesSoap() {
        return super.getPort(new QName("http://tempuri.org/", "InfoSearchServicesSoap"), InfoSearchServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoSearchServicesSoap
     */
    @WebEndpoint(name = "InfoSearchServicesSoap")
    public InfoSearchServicesSoap getInfoSearchServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "InfoSearchServicesSoap"), InfoSearchServicesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INFOSEARCHSERVICES_EXCEPTION!= null) {
            throw INFOSEARCHSERVICES_EXCEPTION;
        }
        return INFOSEARCHSERVICES_WSDL_LOCATION;
    }

}
